### ISSUE TITLE
NameError: uninitialized constant Post on auto_html:rebuild

### ISSUE THREAD

**Issue by jer0m** [dejan/auto_html#109]
Hello,

I try to launch RAILS_ENV=production bundle exec rake auto_html:rebuild CLASS=Post on production but I get this error: NameError: uninitialized constant Post.

It works on my development environment. Do you have an idea of what is happening?

Environment: Rails 3.2.17, Ruby 2.1.1, auto_html 1.6.4

Thanks.

**Comment by dejan** [comment]
Rails integration is gone in new version.
