### ISSUE TITLE
gem not loading

### ISSUE THREAD

**Issue by lucasts** [dejan/auto_html#13]
In a running app, I'm putting the auto_html in gemfile, bundle install but none methods from autohtml seems to work.

rails server load normally, but auto_html method, and auto_html_for doesn`t work 
always get errors like:
    undefined method`auto_html' for #<#Class:0x00000102c63330:0x00000102c60ae0>

I know is a loading problem, but I am not getting any error, and I use many others gems.

any clue

**Comment by iGhost** [comment]
The same issue ```uninitialized constant ApplicationHelper::AutoHtml```
