### ISSUE TITLE
valid auto_html filters

### ISSUE THREAD

**Issue by nivla** [dejan/auto_html#142]
Hi, i have two questions.

This is  my code.

    html_content = auto_html('somevideolink') do
        youtube(:width => 400, :height => 250, :autoplay => false)
        vimeo(:width => 400, :height => 250, :autoplay => false)
    end

1. There is way for match all kind url videos supported in auto_html?
2. Can the method return an empty content if not passed the filters?, because i want to know if the url passed return a valid video link.

Thanks so much.

**Comment by dejan** [comment]
No, there's no way to do this currently.
