### ISSUE TITLE
How can I create my own filter?

### ISSUE THREAD

**Issue by swaathi** [dejan/auto_html#146]

**Comment by spkprav** [comment]
You can simply create a file in initializers folder (maybe `auto_html.rb`) and add your own filters. 
Example filter to find mentions and link to the respective user provided below:

```
AutoHtml.add_filter(:link_to_mentions).with({}) do |text, options|
  text.scan(/(?:\s|^)(?:@(?!\d+(?:\s|$)))(\w+)(?=\s|$)/i).flatten.each do |mention|
    text = text.gsub("@"+mention,"<a href=\"/#{mention}\">@#{mention}</a>")
  end
  text
end
```

**Comment by swaathi** [comment]
Great! Thank you. I was wondering, how come when I add the filter to the gem directly, it never works? Do I need to require it separately?
