### ISSUE TITLE
Filters for any type of video

### ISSUE THREAD

**Issue by napster3000** [dejan/auto_html#148]
This filter works only for youtube

class Comment < ActiveRecord::Base
  auto_html_for :body do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => true)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

I want something that works for anything. Any Video, Images, google maps anything. How to do it?

**Comment by dejan** [comment]
Closing as obosolete.
