### ISSUE TITLE
auto_html takes up 12.8 MB of memory on load

### ISSUE THREAD

**Issue by jontonsoup** [dejan/auto_html#149]
I've been profiling memory issues on my rails app and found that auto_html takes up 12.8 MB. This seems pretty high to me. Can anyone confirm that this is happening in their app?

**Comment by dgilperez** [comment]
Not in my case. `derailed bundle:mem` output: 

    auto_html: 1.2656 MiB (Also required by: auto_html/railtie)

**Comment by dejan** [comment]
Closing as obsolete.
