### ISSUE TITLE
Soundcloud filter

### ISSUE THREAD

**Issue by Rovel** [dejan/auto_html#154]
All soundcloud links gives a 500 error:

Completed 500 Internal Server Error in 50ms (ActiveRecord: 7.8ms)

ActionView::Template::Error (bad URI(is not URI?): http://soundcloud.com/cadumarino/"):

I am missing something? maybe updating the gem resolves?  I'm using auto_html (1.6.4)
to update do I need to rebuild?

Thanks

**Comment by colemerrick** [comment]
If you've requested data from Soundcloud's api recently, for say a song or user, their permalink url has changed from http to https...  may be what your looking for.

**Comment by dejan** [comment]
Closing as it's no longer a bundled filter.
