### ISSUE TITLE
Use this w/o DB worries. No strings attached.

### ISSUE THREAD

**Issue by nofxx** [dejan/auto_html#156]
Not sure I missed something very naive, but there's not a (documented at least) way to auto html a chunk w/o including in a class with AR or Mongoid.
I actually have a objective/scenario where I need to auto html on demand or don't write or cache the html.
Using this:

```
  def html
    Class.new.extend(AutoHtml).auto_html text do
      html_escape
      image
      youtube(:width => 400, :height => 250, :autoplay => true)
      link :target => "_blank", :rel => "nofollow"
      simple_format
    end
  end
```

Would be simpler with a lil patch to auto_html module:

    module_function :auto_html

http://stackoverflow.com/questions/322470/can-i-invoke-an-instance-method-on-a-ruby-module-without-including-it

**Comment by dejan** [comment]
Closing as obsolete.
