### ISSUE TITLE
NameError: uninitialized constant HTML after upgrading to Rails 4.2.4

### ISSUE THREAD

**Issue by dgilperez** [dejan/auto_html#159]
Hi!

I'm seeing a `NameError: uninitialized constant HTML` exception when persisting models with 

    auto_html_for :body do
      sanitize
    end

That leads me to think that [this line](https://github.com/dejan/auto_html/blob/27a3c7e52bff0a67bf9e4166db03181429157057/lib/auto_html/filters/sanitize.rb#L4) is the cause of the problem. 

This happens only after upgrading to Rails 4.2.3, it was working before that with Rails 4.1. Gem version auto_html (1.6.4).

Thanks!

**Comment by whistlerbrk** [comment]
It is, the WhiteListSanitizer was moved into a separate gem.

My branch addresses this, but I see that development work in this, the official, has resumed. I can send a PR but I don't know if the test suite will run.

**Comment by whistlerbrk** [comment]
https://github.com/dejan/auto_html/compare/master...whistlerbrk:master

I have to rebase off of official and cherry-pick a few of my commits. That'll take a minute, but this:

https://github.com/whistlerbrk/auto_html/blob/56085d256545c1997da9d35fa155c8cc7c0e90ed/lib/auto_html/filters/sanitize.rb

Solves it if you add the `gem 'rails-html-sanitizer'`

**Comment by dgilperez** [comment]
Thanks @whistlerbrk!

I was looking into it and just sent a PR to fix this, exactly with the same idea of yours. I'm not sure it will be added fast since there seems to be quite a lot of stalled PRs ... I think I'll just use my branch for the meanwhile. In any case: are you actively maintaining the gem, if it is not?

**Comment by dgilperez** [comment]
Ok, now I read your first message with *development work in this, the official, has resumed*. Sorry! I'll be looking forward to a stable and updated branch, and if the official is that'd be best. Thanks a lot anyway!

**Comment by dgilperez** [comment]
Sorry for a 3rd message but, how do you know development has resumed? I see that last commit on master is from the beginning of february and quite a few of PRs remain unattended ...

**Comment by whistlerbrk** [comment]
I was maintaining my own branch but it looks like at @dejan is active
again. Would love to contribute here in general though :)

**Comment by dmitry** [comment]
May be it's time start to use better sanitize, like this gem: https://github.com/rgrove/sanitize ?

**Comment by dejan** [comment]
Obsolete as new version no longer provides Rails integration.

**Comment by dgilperez** [comment]
Wow, @dejan that was a huge rewrite! 

Are you going to write up about the reasons behind it and provide some hints to upgrade? Some ideas about how to use the new auto_html with Rails would also be appreciated, as well as some hints on how to implement custom filters. Now that Youtube filter is gone, we'd need to implement it ourselves if we want to upgrade!

Cheers :)
