### ISSUE TITLE
Add facebook video filter

### ISSUE THREAD

**Issue by dmitry** [dejan/auto_html#164]
Convert from `https://www.facebook.com/machegomez/videos/vb.1538401847/10207082445889727/?type=2&theater` to `http://www.facebook.com/video/embed?video_id=10207082445889727`

**Comment by dejan** [comment]
No. Bundled filter list should be minimal.

**Comment by dmitry** [comment]
@dejan would be nice to have something like https://github.com/rack/rack-contrib for rack.

**Comment by dejan** [comment]
@dmitry :+1: nice idea, thanks. I've started on this. I'll update the readme when it's done.
