### ISSUE TITLE
Access object within filter

### ISSUE THREAD

**Issue by baldwindavid** [dejan/auto_html#17]
Is there any way to get at the object that this is being called on from within a filter?  I would like to make a filter for Liquid templating, but need to pass the object itself into the render rather than just text.

``` ruby
AutoHtml.add_filter(:liquid).with({}) do |text, options|
  Liquid::Template.parse(text).render(options)
end
```

**Comment by selivandex** [comment]
+1

**Comment by dejan** [comment]
Closing as obsolete.
