### ISSUE TITLE
undefined method `auto_html_for' 

### ISSUE THREAD

**Issue by fabiancarlos** [dejan/auto_html#170]
Guys, having receiving this => undefined method `auto_html_for' 
i add the configuration on my model, and just dont find the method!

**Comment by zrisher** [comment]
This gem went through a significant rewrite for 2.0.0 and removed a lot of functionality. If you can still use it by rewriting to the new syntax go for it, but I had to lock my gem at the previous version:

`gem 'auto_html', '~>1.6.4'`

**Comment by fabiancarlos** [comment]
Yes, i that work for now. Thanks bro

**Comment by dominiccodes** [comment]
Thanks zrisher!
