### ISSUE TITLE
In case of image + emoji it is not working

### ISSUE THREAD

**Issue by curbsaleem** [dejan/auto_html#171]
`AutoHtml::Pipeline.new(AutoHtml::Link.new(target: :_blank), AutoHtml::Emoji.new(width: 20, height: 30)).call("https://www.planwallpaper.com/static/images/canberra_hero_image_JiMVvYU.jpg :joy::heart:️")`

Output is:

`<a href="https://www.planwallpaper.com/static/images/canberra_hero_image_JiMVvYU.jpg <img src="/images/emoji/unicode/1f602.png" class="emoji" title=":joy:" alt=":joy:" height="20" witdh="30" align="absmiddle" /><img src="/images/emoji/unicode/2764.png" class="emoji" title=":heart:" alt=":heart:" height="20" witdh="30" align="absmiddle" />️" target="_blank">https://www.planwallpaper.com/static/images/canberra_hero_image_JiMVvYU.jpg <img src="/images/emoji/unicode/1f602.png" class="emoji" title=":joy:" alt=":joy:" height="20" witdh="30" align="absmiddle" /><img src="/images/emoji/unicode/2764.png" class="emoji" title=":heart:" alt=":heart:" height="20" witdh="30" align="absmiddle" />️</a>`

here you will notice href seems bad.

Can any one plz guide me how we can fix it?

Thanks

**Comment by rupeshfbraju** [comment]
AutoHtml::Pipeline.new(AutoHtml::Link.new(target: :_blank), AutoHtml::Emoji.new(width: 20, height: 30)).call("http://wallpaperchoose.com/public/uploads/image/6991453-fall-wallpaper-hd.jpg :joy::heart:️")

Output is:

<a href="http://wallpaperchoose.com/public/uploads/image/forest-hd-wallpaper-picture-1.jpg <img src="/images/emoji/unicode/1f602.png" class="emoji" title=":joy:" alt=":joy:" height="20" witdh="30" align="absmiddle" /><img src="/images/emoji/unicode/2764.png" class="emoji" title=":heart:" alt=":heart:" height="20" witdh="30" align="absmiddle" />️" target="_blank">http://wallpaperchoose.com/public/uploads/image/hd-island-free-wallpapers.jpg <img src="/images/emoji/unicode/1f602.png" class="emoji" title=":joy:" alt=":joy:" height="20" witdh="30" align="absmiddle" /><img src="/images/emoji/unicode/2764.png" class="emoji" title=":heart:" alt=":heart:" height="20" witdh="30" align="absmiddle" />️</a>

**Comment by dejan** [comment]
I can't reproduce, I'm getting expected string in both cases. Try upgrading to latest gem version.
