### ISSUE TITLE
What happened to Rails integration?

### ISSUE THREAD

**Issue by rbq** [dejan/auto_html#172]
* Is Rails integration currently undocumented, permanently removed, temporarily removed or being refactored into a separate Gem?
* It's really confusing that the scope of the Gem seemingly changed between version numbers. Is this essentially a new project with a different focus now? Will 1.x still be maintained?
* Is it safe to use 1.0 in new Rails projects or is it recommended to look for an alternative, build a wrapper around 2.0 or handle the processing in a more manual way?
* The syntax for defining filters seems to have changed, too. Will there be a guide for upgrading or do you recommend that users of the old version just stop using auto_html?

**Comment by AlexEmerson** [comment]
+1 
What's going on?

**Comment by dgilperez** [comment]
I'm trying to support this gem on its 1.6 version for Rails 4.2+. I'm using it in a couple of small projects in production.

https://github.com/dgilperez/auto_html

Feel free to send PRs at will.

**Comment by rbq** [comment]
@dgilperez Pretty cool, thanks for your work!

**Comment by dejan** [comment]
I'm sorry, I've missed this message:

> Is Rails integration currently undocumented, permanently removed, temporarily removed or being refactored into a separate Gem?

Permanently removed. It's very easy to integrate this gem to any framework.

> It's really confusing that the scope of the Gem seemingly changed between version numbers. Is this essentially a new project with a different focus now? Will 1.x still be maintained?

1.x is not maintained any more.

> Is it safe to use 1.0 in new Rails projects or is it recommended to look for an alternative, build a wrapper around 2.0 or handle the processing in a more manual way? The syntax for defining filters seems to have changed, too. Will there be a guide for upgrading or do you recommend that users of the old version just stop using auto_html?

If it 2.x still brings you value, you're welcome to use it. Otherwise you can use some alternative.

Once again, I'm sorry about the late response.
