### ISSUE TITLE
will_paginate-bootstrap is broken auto_html

### ISSUE THREAD

**Issue by fabiancarlos** [dejan/auto_html#173]
I have put will_paginate-bootstrap on the Gemfile this way, before the auto_html:

gem 'will_paginate-bootstrap', '1.0.1'
gem 'auto_html', '1.6.4'

and than broked the auto_html. Now i put this, after:

gem 'auto_html', '1.6.4'
gem 'will_paginate-bootstrap', '1.0.1'

and worked!
Why??

**Comment by dejan** [comment]
How was it broken? Did you get any errors?

**Comment by fabiancarlos** [comment]
I receive 'auto_html' is undefined

**Comment by dejan** [comment]
Closing this. Recommended version is 2.0.1.
