### ISSUE TITLE
Rails5 deprecation warning

### ISSUE THREAD

**Issue by swaathi** [dejan/auto_html#174]
I've added the auto_html_for block in my model. However when I try to call an object of that model, I get this deprecation warning,

```
DEPRECATION WARNING: #table_exists? currently checks both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only check tables. Use #data_source_exists? instead.
```

For example when I do this on my Answer model,

```
Answer.first
```

**Comment by dejan** [comment]
You are using pre-2 version of auto_html gem that has Rails integration. I no longer maintain that version, please upgrade to new version and write your own Rails integration. Essentially all you have to do is override accessors, something like this: http://stackoverflow.com/a/379576

**Comment by swaathi** [comment]
Oops! Thank you. 😄
