### ISSUE TITLE
Where can I find the emoji image library?

### ISSUE THREAD

**Issue by feliperaul** [dejan/auto_html#183]
Where can I find the emoji image library to use with this gem?

Btw, great work here!

**Comment by dejan** [comment]
Hi @feliperaul, in the new version (2.1.0) the gem uses unicode characters to render emojis. Aliases are used to reference them (e.g. `:hamburger:`). The gem is using gemoji gem which provides this [mapping](https://github.com/github/gemoji/blob/b1c7878afeb260d2ff6dc6655bf3aa7dee498e9c/db/emoji.json). Try out emojis in the live demo here: https://autohtml.rors.org
