### ISSUE TITLE
Want to be able to autolink short domains

### ISSUE THREAD

**Issue by rhiroe** [dejan/auto_html#186]
```rb
AutoHtml::Link.new.call('http://localhost:3000')
#=> "http://localhost:3000"
```

Want to autolink localhost, etc.
If this is not possible, it is inconvenient when checking in the development environment and testing.
Do you have the means in place to make this happen?

Currently, I am using `AutoHtml::Link#call` with a monkey patch in my product.
```rb
module AutoHtml
  class Link
    def call(text)
      Rinku.auto_link(text, :all, attributes, nil, Rinku::AUTOLINK_SHORT_DOMAINS)
    end
  end
end

AutoHtml::Link.new.call('http://localhost:3000')
=> "<a href=\"http://localhost:3000\">http://localhost:3000</a>"
```
How about incorporating this into a gem or making it available?

**Comment by dejan** [comment]
Please open the PR to make the suggested change in the gem: https://github.com/dejan/auto_html/blob/master/lib/auto_html/link.rb#L16

Thanks!

**Comment by rhiroe** [comment]
@dejan 
Thank you. I will make a pull request.
I will be proposing the following changes.

```rb
module AutoHtml
  class Link
    def initialize(target: nil, rel: nil, short_domains: false)
      @target = target
      @rel = rel
      @short_domains = short_domains
    end

    def call(text)
      Rinku.auto_link(text, :all, attributes, nil, flags)
    end

    private

    def flags
      @short_domains ? Rinku::AUTOLINK_SHORT_DOMAINS : 0
    end

  end
end

AutoHtml::Link.new(short_domains: true).call('http://localhost:3000')
```

If it is not in line with this gem philosophy, please point it out.
