### ISSUE TITLE
youtube urls: https and params appearing before v=

### ISSUE THREAD

**Issue by sheldond** [dejan/auto_html#27]
auto_html (1.4.2) doesn't seem to like http__s__ youtube links, for example:

```ruby
 > auto_html("https://www.youtube.com/watch?v=t7NdBIA4zJg") {youtube;}
 => "https://www.youtube.com/watch?v=t7NdBIA4zJg"
```
Also, auto_html doesn't seem to like parameters appearing before the v param in youtube urls, for example:

```ruby
 >  auto_html("http://www.youtube.com/watch?NR=1&v=t7NdBIA4zJg") {youtube;}
 => "http://www.youtube.com/watch?NR=1&v=t7NdBIA4zJg" 
 >  auto_html("http://www.youtube.com/watch?v=t7NdBIA4zJg&NR=1") {youtube;}
 => "<iframe class=\"youtube-player\" type=\"text/html\" width=\"390\" height=\"250\" src=\"http://www.youtube.com/embed/t7NdBIA4zJg\" frameborder=\"0\">\n</iframe>"
```
Note that I copied this url straight from youtube: `https://www.youtube.com/watch?NR=1&v=t7NdBIA4zJg` 

Thanks for this library, I'm hoping to use it in a current project!

**Comment by NeilvB** [comment]
Thanks for writing this library. I'm also hoping to use it in a project. However I'm having the same problem with embedding `https` video URLs. The unit test for correct conversion of an https URL into an embedded youtube link seems to work though.
