### ISSUE TITLE
It doesn't work on Rails3.2.11

### ISSUE THREAD

**Issue by megalomania1982** [dejan/auto_html#65]
I'm using another gem called "acts_as_commentable_with_threading". It automatically creates "models/comment.rb" so I added this to it in order to make it changed to playable thumbnail every time when it's posted. However it doesn't do any. Why is that?
I'm using RoR3.2.11, RInku1.5.0, and auto_html1.5.2

	auto_html_for :body do
		html_escape
		image
		youtube(:width => 400, :height => 250)
		link :target => "_blank", :rel => "nofollow"
		simple_format
	end

**Comment by dejan** [comment]
Obsolete as the Rails integration is gone.
