### ISSUE TITLE
undefined method `auto_html_for' for #<Class:0x00000003c6d038>

### ISSUE THREAD

**Issue by feliksg** [dejan/auto_html#8]
I'm using ruby 1.9.2 with rails 3.0.0, I included auto_html into my gem file like this: gem 'auto_html'
and included this into my model (I have a field called body)

auto_html_for :body do
    html_escape
    image
    youtube(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

however, I am getting an error saying: undefined method `auto_html_for' for #Class:0x00000003c6d038

**Comment by kmaiorini82** [comment]
I am seeing this issue again.  I am using Ruby 2.2.1 and Rails 3.2.22.  I am currently using auto_html 2.0.0.

Any ideas?

**Comment by swaathi** [comment]
I'm seeing this issue with Rails 5, Ruby 2.2.3 and auto_html 2.0.0. Please fix. :( If I use auto_html 1.3.3, Rails 5 throws a deprecation warning.

**Comment by niklasbabel** [comment]
same for me

**Comment by niklasbabel** [comment]
@swaathi hey, did u solve it? I am running Rails 4.2.5 and Ruby 2.3.0p0 and also auto_html 2.0.0 (I guess, just installed it few days ago)

**Comment by swaathi** [comment]
I just started using this version of it, https://github.com/dgilperez/auto_html/. Or you can downgrade to 1.6.4 (I think) to get this working again, but then 1.6.4 has warnings with Rails 5. However, the dgilperez version fixes all of this. Though it is not by the author himself, but this maintainer has committed somewhat. 

_
Swaathi K
CTO, Skcript
